# Nom du workflow qui apparaîtra dans l'onglet "Actions" de GitHub
name: Deploy to Firebase Hosting

# Se déclenche à chaque "push" sur la branche "main"
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Récupère le code du dépôt
      - uses: actions/checkout@v3

      # Étape 2: Installe les dépendances
      - name: Install dependencies
        run: npm ci

      # Étape 3: Construit l'application React
      - name: Build
        run: npm run build
        env:
          # Utilise le secret pour la clé API Gemini
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}

      # Étape 4: Déploie sur Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          # Ajout de l'ID du projet pour corriger l'erreur
          projectId: 268165687076